version: '3.7'
services:
  postgres:
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # initial db in order
      - ../repository-impl/src/main/sql/domain/1.0__initial.sql:/docker-entrypoint-initdb.d/1.sql
      - ../repository-impl/src/main/sql/dbinit/1.0__initial.sql:/docker-entrypoint-initdb.d/2.sql
      #      - ./postgres-data:/var/lib/postgresql/data
