spring:
  application:
    name: codes-planet
  main:
    banner-mode: "off"
logging:
  level:
    root: info
    io.ebean: info
grpc:
  port: 9090

server:
  port: 8080


management:
  server:
    port: 30000
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    web:
      base-path: /monitor
      exposure:
        exclude: env,beans
        include: health,prometheus,loggers,shutdown
  metrics:
    tags:
      application: ${spring.application.name}
