spring:
  web:
    resources:
      static-locations: classpath:/static/
  application:
    name: codes-planet
  main:
    banner-mode: "off"
#  mvc:
#    static:
#      static-path-pattern: ""
#    view:
#      prefix: classpath:/web-ui/public/
#      suffix: .html
logging:
  level:
    root: info
    io.ebean: info
grpc:
  port: 9090

server:
  port: 8080

codeplanet:
  db:
    writeonly:
      url: jdbc:postgresql://localhost:5438/postgres
      username: postgres
      password: postgres
      db_name: postgres
      driver_class: "org.postgresql.Driver"
      packages: "codes.showme.domain"
    readonly:
      url: jdbc:postgresql://localhost:5438/postgres
      username: postgres
      password: postgres
      db_name: postgres
      driver_class: "org.postgresql.Driver"
      packages: "codes.showme.domain"
  crypto:
    account:
      algorithmName: "SHA-256"
      hashIterations: 3
      randomSaltNum: 6
management:
  server:
    port: 30000
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    shutdown:
      enabled: true
    web:
      base-path: /monitor
      exposure:
        exclude: env,beans
        include: health,prometheus,loggers,shutdown
  metrics:
    tags:
      application: ${spring.application.name}
