-- apply changes
create table cp_teams (
  id                            bigint generated by default as identity not null,
  create_time                   timestamptz,
  version                       integer not null,
  name                          varchar(125),
  constraint pk_cp_teams primary key (id)
);

