-- apply changes
create table cp_account (
  id                            bigint generated by default as identity not null,
  create_time                   timestamptz,
  email_validated               boolean default false not null,
  version                       integer not null,
  name                          varchar(128),
  email                         varchar(128),
  password                      varchar(32),
  profile                       json,
  constraint pk_cp_account primary key (id)
);

